version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - USE_DEMO_DATA=${USE_DEMO_DATA}
      - SAP_B1_ENDPOINT=${SAP_B1_ENDPOINT}
      - SAP_B1_USERNAME=${SAP_B1_USERNAME}
      - SAP_B1_PASSWORD=${SAP_B1_PASSWORD}
    command: flask run --host=0.0.0.0
